DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    type TEXT NOT NULL,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    password TEXT NOT NULL
);

DROP TABLE IF EXISTS rentals;
CREATE TABLE IF NOT EXISTS rentals (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ownerId INTEGER UNSIGNED NOT NULL,
	address TEXT NOT NULL,
	city TEXT NOT NULL,
	price NUMERIC UNSIGNED NOT NULL,
	type TEXT NOT NULL,
	rented INTEGER UNSIGNED NOT NULL,
    image TEXT,

    FOREIGN KEY(ownerId) REFERENCES users(id)
);